import { Producto } from 'src/Productos/entitie/productos.entity';
import { Categoria } from 'src/Categorias/entitie/categorias.entitie';
import { v4 as uuid } from 'uuid'; // Importar la función para generar UUIDs

export const productosMock: Producto[] = [
  {
    id: uuid(), // Generar un UUID para cada producto
    name: 'Producto 1',
    description: 'Descripción del producto 1',
    price: 100,
    stock: 50,
    isActive: true,
    fechaCreación: new Date(),
    fechaActualización: new Date(),
    categoria: { id: '25c209d3-6b2e-4eb7-86c2-e54fb2e2a252' } as Categoria,
    imageUrl: 'http://example.com/product1.jpg',
  },
  // {
  //   id: uuid(),
  //   name: 'Producto 2',
  //   description: 'Descripción del producto 2',
  //   price: 200,
  //   stock: 30,
  //   isActive: true,
  //   fechaCreación: new Date(),
  //   fechaActualización: new Date(),
  //   categoria: { id: '2' } as Categoria,
  //   imageUrl: 'http://example.com/product2.jpg',
  // },
  // {
  //   id: uuid(),
  //   name: 'Producto 3',
  //   description: 'Descripción del producto 3',
  //   price: 150,
  //   stock: 25,
  //   isActive: true,
  //   fechaCreación: new Date(),
  //   fechaActualización: new Date(),
  //   categoria: { id: '3' } as Categoria,
  //   imageUrl: 'http://example.com/product3.jpg',
  // },
  // {
  //   id: uuid(),
  //   name: 'Producto 4',
  //   description: 'Descripción del producto 4',
  //   price: 120,
  //   stock: 40,
  //   isActive: true,
  //   fechaCreación: new Date(),
  //   fechaActualización: new Date(),
  //   categoria: { id: '4' } as Categoria,
  //   imageUrl: 'http://example.com/product4.jpg',
  // },
  // {
  //   id: uuid(),
  //   name: 'Producto 5',
  //   description: 'Descripción del producto 5',
  //   price: 250,
  //   stock: 20,
  //   isActive: true,
  //   fechaCreación: new Date(),
  //   fechaActualización: new Date(),
  //   categoria: { name: '' } as Categoria,
  //   imageUrl: 'http://example.com/product5.jpg',
  // },
  // {
  //   id: uuid(),
  //   name: 'Producto 6',
  //   description: 'Descripción del producto 6',
  //   price: 300,
  //   stock: 15,
  //   isActive: true,
  //   fechaCreación: new Date(),
  //   fechaActualización: new Date(),
  //   categoria: { id: '6' } as Categoria,
  //   imageUrl: 'http://example.com/product6.jpg',
  // },
  // {
  //   id: uuid(),
  //   name: 'Producto 7',
  //   description: 'Descripción del producto 7',
  //   price: 90,
  //   stock: 60,
  //   isActive: true,
  //   fechaCreación: new Date(),
  //   fechaActualización: new Date(),
  //   categoria: { id: '7' } as Categoria,
  //   imageUrl: 'http://example.com/product7.jpg',
  // },
  // {
  //   id: uuid(),
  //   name: 'Producto 8',
  //   description: 'Descripción del producto 8',
  //   price: 130,
  //   stock: 35,
  //   isActive: true,
  //   fechaCreación: new Date(),
  //   fechaActualización: new Date(),
  //   categoria: { id: '8' } as Categoria,
  //   imageUrl: 'http://example.com/product8.jpg',
  // },
  // {
  //   id: uuid(),
  //   name: 'Producto 9',
  //   description: 'Descripción del producto 9',
  //   price: 180,
  //   stock: 45,
  //   isActive: true,
  //   fechaCreación: new Date(),
  //   fechaActualización: new Date(),
  //   categoria: { id: '9' } as Categoria,
  //   imageUrl: 'http://example.com/product9.jpg',
  // },
  // {
  //   id: uuid(),
  //   name: 'Producto 10',
  //   description: 'Descripción del producto 10',
  //   price: 110,
  //   stock: 55,
  //   isActive: true,
  //   fechaCreación: new Date(),
  //   fechaActualización: new Date(),
  //   categoria: { id: '10' } as Categoria,
  //   imageUrl: 'http://example.com/product10.jpg',
  // },
];
